<Project Sdk="Dalamud.NET.Sdk/15.0.0">

    <PropertyGroup>
        <Author>Jackie</Author>
        <Version>1.0.0.0</Version>
        <Description>Walk onto your target's spot and match the way they're facing.</Description>
        <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
        <TargetFramework>net10.0-windows7.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

</Project>
